kind: project
metadata:
  name: myproj-test
spec:
  description: my new project
  functions:
  - url: ./src/queue-manager/queue_manager.py
    name: queue-manager
    kind: nuclio
  workflows: []
  artifacts: []
  conda: ''
  source: ''
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
