kind: project
metadata:
  name: myproj-test
spec:
  description: my new project
  functions:
  - url: ./src/queue-manager/function.yaml
    name: queue-manager
  workflows: []
  artifacts: []
  conda: ''
  source: ''
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
